version: "3.9"

services:
  db:
    image: postgres:15
    container_name: phonebook_postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myprojectuser
