version: "3.5"

services:
  db:
    image: postgres:15
    container_name: phonebook_postgres
    env_file:
      - .env
  phonebook:
    image: phonebook_docker:latest
    container_name: phonebook_docker
    depends_on:
      - db
    volumes:
      - static_volume:/phonebook/static
    env_file:
      - .env
    command: >
      bash -c "dos2unix ./manage.py && \
      ./manage.py collectstatic --noinput && \
      ./manage.py migrate && \
      ./manage.py loaddata db.json \
       gunicorn -b 0.0.0.0:8000 DjangoPhonebook.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: phonebook_nginx
    image: phonebook_nginx
    volumes:
      - static_volume:/phonebook/static
    depends_on:
      - phonebook
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume: