version: "3.9"

services:
  db:
    image: postgres:15
    container_name: phonebook_postgres
    volumes:
      - ~/.pg/pg_data/phonebook:/var/lib/postgresql/data
    env_file:
      - .env
  phonebook:
    image: phonebook_docker:latest
    container_name: phonebook_docker
    depends_on:
      - db
    volumes:
      - static_volume:/phonebook/static
    env_file:
      - .env
    command: >
      bash -c "dos2unix ./manage.py && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 DjangoPhonebook.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: phonebook_nginx
    image: phonebook_nginx
    volumes:
      - static_volume:/phonebook/static
    depends_on:
      - phonebook
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"


volumes:
  static_volume: