# Generated by Django 5.0.3 on 2024-03-26 07:45

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование организации')),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='phonebook.division', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150, verbose_name='фамилия')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='должность')),
                ('phone', models.CharField(max_length=150, verbose_name='телефон')),
                ('short_phone', models.CharField(blank=True, max_length=20, verbose_name='короткий №')),
                ('cabinet', models.CharField(blank=True, max_length=150, verbose_name='кабинет')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150)),
                ('division', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='phonebook.division', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Телефоны',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['create_at'],
            },
        ),
    ]
